# Generated by Django 4.0.3 on 2022-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('post_text', models.CharField(max_length=250)),
            ],
        ),
    ]
